name: Generate Neon Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create dist folder
        run: mkdir -p dist

      - name: Generate Neon Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Adiwebtya
          outputs: |
            dist/github-contribution-grid-snake-dark.svg
            dist/github-contribution-grid-snake-neon.svg?color_snake=#00F0FF,#7D19F8,#FF00E6&palette=github-dark

      - name: Push snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
